# Name of your application. Used to uniquely configure containers.
service: doneyet

# Name of the container image.
image: fernandoleano/doneyet

# Deploy to these servers.
servers:
  web:
    - 104.131.92.251

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  host: doneyet.ai

# Where you keep your container images.
registry:
  server: hub.docker.com
  username: fernandoleano
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true

# Aliases are triggered with "bin/kamal <alias>".
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for Active Storage files.
volumes:
  - "doneyet_storage:/rails/storage"

# Bridge fingerprinted assets between versions
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64

# Use accessory services for PostgreSQL
accessories:
  db:
    image: postgres:16
    host: 104.131.92.251
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_DB: doneyet_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
